# Walkthrough

### Imports

In [75]:
from LyndonWords import *
import numpy as np

## Basics

In [76]:
'''
    Most things are done through the Rootsystem object 
    
    initialization requires an ordering given as an iterable and a string signifying type
    which is from A-G
'''

#This generates the rootSystem correspond to F_4^{(1)} with the ordering 1<0<2<3<4
rootsys = rootSystem(np.array([1,0,2,3,4]),'F')

In [77]:
'''
    The other primary object you will encounter is the word object
    
    initialization of words is done through the rootSystem object 
'''

#Gets the standard lyndon word associated with root 
# \alpha_0 + \alpha_1 + 2\alpha_2 + 4\alpha_3 + 2 \alpha_4

w = rootsys.SL([1, 1, 2, 4, 2])[0]

'''
    Additionally, one can compare words easily with the standard operators
'''

w1 = rootsys.SL([0,1,0,0,0])[0]
w2 = rootsys.SL([1,0,0,0,0])[0]

print(w1)
print(w2)
print(rootsys.ordering)
print(w1 < w2)

1
0
1<0<2<3<4
True


In [78]:
'''
    To print words, you will generally want to call 
    word.no_commas() to convert to a easier to read string
'''

print(w.no_commas())

1234342330


In [79]:
'''
Since there are multiple imaginary standard Lyndon words, rootSystem.SL() will always return a list
'''

#The following prints all imaginary words of height |\delta| 
for i in rootsys.SL(rootsys.delta):
    print(i.no_commas())

123430123432
123431234320
123401234323
123320123434


In [80]:
'''
The rootSystem object will automatically initialize the appropriate \delta
This can be used to quickly find the standard Lyndon words associated with roots of large height
'''

print(rootsys.delta)

#The following generates the standard Lyndon word associated with 10*\delta + \alpha_1
rootsys.SL(rootsys.delta * 10 + [0,1,0,0,0])

'''
    In addition rootSystem.baseRoots is also automatically generated which is the set of
    all roots of heights <= |\delta|
'''

print(rootsys.baseRoots[:5])

[1 2 3 4 2]
[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [1 0 0 0 0]]


In [81]:
'''
    Generation of standard Lyndon words is cached so as soon as a 
    given height is computed it can be accessed quickly.
    
    In addition there are several optimizations which take place when generating words,
    making even E8 take only seconds to generate words of sufficient height
'''

#Creates E8 rootSystem with the given ordering
E8 = rootSystem([2,4,8,7,0,1,6,5,3],'E')

#Generates all words of height less than or equal to 5|\delta|
E8.generate_up_to_delta(5)

In [82]:
'''
    Chains are of particular interest, calling rootSystem.get_chain(root,min_delta=0)
    will return the chain associated with that root for all words which have been generated,
    if you would like there to be at least some number of words, specify that in min_delta
'''

for i in rootsys.get_chain([1,0,0,0,0],4)[:4]:
    print(i.no_commas())

0
1234301234320
1234301234321234301234320
1234301234321234301234321234301234320


In [83]:
'''
    Additionally, covering words to 'delta format' can greatly ease readability 
    
    The conversion is done greedily from left to right
'''

#Parses \SL_2(5\delta) into delta format 
parsed = rootsys.parse_to_delta_format(rootsys.SL(rootsys.delta*5)[1])

#The quotes are read as expected, the block [i,j] is read as \SL_i(\delta) repeated j times
print(parsed)

['12343123432', [1, 4], '0']


In [84]:
'''
    Using this block format, we can find the periodicity of chains
    
    Be weary however, the periodicity function generates words until it is certain a chain
    is of a given periodicity, so E7,E8 can take a while to run
'''
#Prints the delta form of the given root
print(rootsys.parse_to_delta_format(rootsys.SL(rootsys.delta*13 + [1, 1, 3, 4, 2])[0]))

#Prints the periodicity
print(rootsys.periodicity([1, 1, 3, 4, 2]))

[[1, 2], '3', [1, 1], '123432', [1, 1], '0', [1, 1], '123432', [1, 2], '3', [1, 1], '123432', [1, 1], '0123434', [1, 1], '123432', [1, 1], '0']
9


In [85]:
'''
    Additionally, one can quickly get information related to monotonicity of a given chain
    
    -1 indicates decreasing
    1 indicates increasing
'''

#returns monotonicity of chain(\alpha_1)
rootsys.get_monotonicity([0,1,0,0,0])

'''
    One can also get all increasing/decreasing chains 
'''

#Prints monotone increasing chains
print(rootsys.get_monotone_increasing()[:3])

#Prints monotone decreasing chains
print(rootsys.get_monotone_decreasing()[:3])

[array([0, 1, 0, 0, 0]), array([0, 1, 1, 0, 0]), array([1, 1, 0, 0, 0])]
[array([0, 0, 1, 0, 0]), array([0, 0, 0, 1, 0]), array([0, 0, 0, 0, 1])]


In [86]:
'''
    m_k() and M_k() can also be computed by the rootSystem object
    
    The return will only be a single number since the flags are compatible, and is 1-indexed
'''

#Prints m_k
print(rootsys.m_k([0,1,0,0,0]))

#Prints M_k
print(rootsys.M_k([0,1,0,0,0]))


4
2


In [87]:
'''
    Both costandard and standard factorization of words can be found via the rootSystem object
'''

#Prints costandard factorization 
print([i.no_commas() for i in rootsys.costfac(rootsys.SL(rootsys.delta)[2])])

#Prints standard factorization
print([i.no_commas() for i in rootsys.standfac(rootsys.SL(rootsys.delta)[2])])

['12340', '1234323']
['12340123432', '3']


In [88]:
'''
    Additionally one can find all \beta, \gamma such that \beta + \gamma = \alpha
'''

#Prints all splittings of \delta + \alpha_1 into the sum of two roots
print(*rootsys.get_decompositions(rootsys.delta + [0,1,0,0,0]),sep='\n')

(array([0, 1, 0, 0, 0]), array([1, 2, 3, 4, 2]))
(array([0, 1, 1, 0, 0]), array([1, 2, 2, 4, 2]))
(array([1, 1, 0, 0, 0]), array([0, 2, 3, 4, 2]))
(array([0, 1, 1, 1, 0]), array([1, 2, 2, 3, 2]))
(array([0, 1, 1, 1, 1]), array([1, 2, 2, 3, 1]))
(array([0, 1, 1, 2, 0]), array([1, 2, 2, 2, 2]))
(array([0, 1, 1, 2, 1]), array([1, 2, 2, 2, 1]))
(array([0, 1, 1, 2, 2]), array([1, 2, 2, 2, 0]))
(array([1, 2, 2, 2, 0]), array([0, 1, 1, 2, 2]))
(array([1, 2, 2, 2, 1]), array([0, 1, 1, 2, 1]))
(array([1, 2, 2, 3, 1]), array([0, 1, 1, 1, 1]))
(array([1, 2, 2, 2, 2]), array([0, 1, 1, 2, 0]))
(array([1, 2, 2, 3, 2]), array([0, 1, 1, 1, 0]))
(array([0, 2, 3, 4, 2]), array([1, 1, 0, 0, 0]))
(array([1, 2, 2, 4, 2]), array([0, 1, 1, 0, 0]))
(array([1, 2, 3, 4, 2]), array([0, 1, 0, 0, 0]))


In [89]:
'''
    The last part of this is we can calculate the W set used in the paper, for imaginary heights
'''

#Prints the W set for \delta
print(*rootsys.text_W_set(1),sep='\n')

('123430', '123432')
('12343', '1234320')
('12343123432', '0')
('12343123430', '2')
('12340', '1234323')
('1234012343', '23')
('12340123432', '3')
('1234', '12343230')
('123412340', '233')
('123320', '123434')
('1233201234', '34')
('12332012343', '4')
('12332', '1234340')
('12330', '1234342')
('123301234', '234')
('1233', '12343420')
('1230', '12343423')
('12301234', '2343')
('123', '123434230')
('1231230', '23434')
('120', '123434233')
('12', '1234342330')
('10', '1234342332')
('1', '12343423320')


This concludes the basics of the library